#!/bin/bash
# Setup GitHub Pages for Privacy Policy
# Run this script to host your privacy policy online

echo "=== GitHub Pages Setup ==="
echo ""
echo "1. Create a new GitHub repository:"
echo "   - Go to https://github.com/new"
echo "   - Repository name: iraqi-pos"
echo "   - Make it Public"
echo "   - Click 'Create repository'"
echo ""
echo "2. Push your code:"
echo "   cd \"/New Project (4)-/iraqi-pos\""
echo "   git remote add origin https://github.com/YOUR_USERNAME/iraqi-pos.git"
echo "   git add privacy-policy/"
echo "   git commit -m 'Add privacy policy'"
echo "   git push -u origin master"
echo ""
echo "3. Enable GitHub Pages:"
echo "   - Go to your repo on GitHub"
echo "   - Click 'Settings'"
echo "   - Click 'Pages' (left sidebar)"
echo "   - Under 'Source', select 'main' branch"
echo "   - Click 'Save'"
echo ""
echo "4. Your privacy policy will be live at:"
echo "   https://YOUR_USERNAME.github.io/iraqi-pos/privacy-policy/"
echo ""
echo "5. Use this URL in Play Console:"
echo "   https://YOUR_USERNAME.github.io/iraqi-pos/privacy-policy/"
echo ""
echo "=== Done! ==="
